export const IsharesData = [
  {
    id: 1,
    scrip: "AADR",
    quantity: 430,
    price: "$50.30",
    avgCost: "$41.75",
    type: "Mutual Fund",
  },
  {
    id: 2,
    scrip: "MFEM",
    quantity: 210,
    price: "$23.20",
    avgCost: "$22.50",
    type: "Mutual Fund",
  },
  {
    id: 3,
    scrip: "JPEM",
    quantity: 328,
    price: "$52.50",
    avgCost: "$56.70",
    type: "Mutual Fund",
  },
  {
    id: 4,
    scrip: "KEMQ",
    quantity: 801,
    price: "$20.40",
    avgCost: "$22.24",
    type: "Mutual Fund",
  },
  {
    id: 5,
    scrip: "KLDW",
    quantity: 523,
    price: "$32.90",
    avgCost: "$26.32",
    type: "ETF's",
  },
  {
    id: 6,
    scrip: "KOIN",
    quantity: 335,
    price: "$25.40",
    avgCost: "$25.40",
    type: "ETF's",
  },
];
